# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialog_reconnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogReconnect(object):
    def setupUi(self, DialogReconnect):
        DialogReconnect.setObjectName("DialogReconnect")
        DialogReconnect.resize(211, 106)
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::ApplicationExit")
        DialogReconnect.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(DialogReconnect)
        self.label.setGeometry(QtCore.QRect(9, 9, 170, 36))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogReconnect)
        self.buttonBox.setGeometry(QtCore.QRect(20, 70, 171, 26))
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(DialogReconnect)
        self.buttonBox.accepted.connect(DialogReconnect.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogReconnect.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogReconnect)

    def retranslateUi(self, DialogReconnect):
        _translate = QtCore.QCoreApplication.translate
        DialogReconnect.setWindowTitle(_translate("DialogReconnect", "Error"))
        self.label.setText(_translate("DialogReconnect", "Connection failed. Please reconnect the CABRA."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogReconnect = QtWidgets.QDialog()
    ui = Ui_DialogReconnect()
    ui.setupUi(DialogReconnect)
    DialogReconnect.show()
    sys.exit(app.exec_())
