# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialog_tone_burst.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogToneBurst(object):
    def setupUi(self, DialogToneBurst):
        DialogToneBurst.setObjectName("DialogToneBurst")
        DialogToneBurst.resize(270, 173)
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::AudioVolumeHigh")
        DialogToneBurst.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogToneBurst)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formCLick = QtWidgets.QFormLayout()
        self.formCLick.setObjectName("formCLick")
        self.labelClickDuration = QtWidgets.QLabel(DialogToneBurst)
        self.labelClickDuration.setObjectName("labelClickDuration")
        self.formCLick.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelClickDuration)
        self.spinClickDuration = QtWidgets.QSpinBox(DialogToneBurst)
        self.spinClickDuration.setMinimum(1)
        self.spinClickDuration.setProperty("value", 10)
        self.spinClickDuration.setObjectName("spinClickDuration")
        self.formCLick.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinClickDuration)
        self.labelCycleDuration = QtWidgets.QLabel(DialogToneBurst)
        self.labelCycleDuration.setObjectName("labelCycleDuration")
        self.formCLick.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelCycleDuration)
        self.spinCycleDuration = QtWidgets.QSpinBox(DialogToneBurst)
        self.spinCycleDuration.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.spinCycleDuration.setMinimum(1)
        self.spinCycleDuration.setProperty("value", 30)
        self.spinCycleDuration.setObjectName("spinCycleDuration")
        self.formCLick.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinCycleDuration)
        self.labelNClicks = QtWidgets.QLabel(DialogToneBurst)
        self.labelNClicks.setObjectName("labelNClicks")
        self.formCLick.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelNClicks)
        self.spinNClicks = QtWidgets.QSpinBox(DialogToneBurst)
        self.spinNClicks.setMinimum(50)
        self.spinNClicks.setMaximum(3000)
        self.spinNClicks.setSingleStep(50)
        self.spinNClicks.setProperty("value", 500)
        self.spinNClicks.setObjectName("spinNClicks")
        self.formCLick.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinNClicks)
        self.verticalLayout.addLayout(self.formCLick)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogToneBurst)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DialogToneBurst)
        self.buttonBox.accepted.connect(DialogToneBurst.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogToneBurst.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogToneBurst)

    def retranslateUi(self, DialogToneBurst):
        _translate = QtCore.QCoreApplication.translate
        DialogToneBurst.setWindowTitle(_translate("DialogToneBurst", "Tone burst setup"))
        self.labelClickDuration.setText(_translate("DialogToneBurst", "Click duration:"))
        self.spinClickDuration.setSuffix(_translate("DialogToneBurst", " [ms]"))
        self.labelCycleDuration.setText(_translate("DialogToneBurst", "Cycle duration:"))
        self.spinCycleDuration.setSuffix(_translate("DialogToneBurst", " [ms]"))
        self.labelNClicks.setText(_translate("DialogToneBurst", "Number of clicks:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogToneBurst = QtWidgets.QDialog()
    ui = Ui_DialogToneBurst()
    ui.setupUi(DialogToneBurst)
    DialogToneBurst.show()
    sys.exit(app.exec_())
